### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by zhuanghao123** [T-urning/SIT_TrajectoryPrediction#1]
您好，请问数据集放在哪里，您的文档里没有显示data文件夹

**Comment by T-urning** [comment]
您好，自己新建这个就行。哈哈我用 git 上传的时候把那个文件 ignore


------------------ 原始邮件 ------------------
发件人: zhuanghao123 ***@***.***&gt;
发送时间: 2022年6月16日 17:23
收件人: T-urning/SIT_TrajectoryPrediction ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[T-urning/SIT_TrajectoryPrediction] 求教 (Issue #1)





 
您好，请问数据集放在哪里，您的文档里没有显示data文件夹

**Comment by zhuanghao123** [comment]
谢谢，我直接来一波一键三连
