### ISSUE TITLE
data_preprocess

### ISSUE THREAD

**Issue by Ocean728** [T-urning/SIT_TrajectoryPrediction#2]
你好，根据preprocess_data.m处理的数据中似乎没有速度这个特征吧，只有位置x, y

**Comment by T-urning** [comment]
是的，速度、加速度等特征可以在 Python 代码中计算，如 https://github.com/T-urning/SIT_TrajectoryPrediction/blob/ac3362fb176562ab10c49d8a9ddac76ed12af52d/main.py#L76

**Comment by Ocean728** [comment]
谢谢解答，这里还有几个疑问：

1、提出的方法是对轨迹进行预测，那么实际的做法是对速度预测。预测的速度是怎么转化为位置坐标的呢？
2、将所有的坐标和速度数据归一化为(-1, 1)之间是用什么方法，tanh函数吗？
3、每个时刻的车辆总数都为22，不足22辆是通过什么方法解决的呀？
4、TPHGI和GRIP代表的是什么模型？

**Comment by T-urning** [comment]
1. 已知 t1 时刻的位置坐标，如果能预测 t1 至 t2，以及 t2 至 t3 时刻间的速度，那么我们是不是就可以计算到 t3 时刻的位置了。
2. 这一部分后期在代码里有所改动（出于疏忽忘记在论文中做相应修改了），代码里直接使用 $\frac{x}{x_{max}}$ 将数据映射到 (0, 1] 的范围，具体可见：https://github.com/T-urning/SIT_TrajectoryPrediction/blob/ac3362fb176562ab10c49d8a9ddac76ed12af52d/main.py#L83
3. 用 0 填充，具体可见：https://github.com/T-urning/SIT_TrajectoryPrediction/blob/ac3362fb176562ab10c49d8a9ddac76ed12af52d/feeder_ngsim.py#L106
4. TPHGI 是实验中废弃的一个优化版本，GRIP 是论文 [GRIP: Graph-based Interaction-aware Trajectory Prediction](https://ieeexplore.ieee.org/abstract/document/8917228) 中的，在我论文中有引用。

**Comment by Ocean728** [comment]
哦原来是这样，只是在计算均方根误差时没有在代码中找到如何将预测的速度换算成位置，不知是我没看懂还是计算的是速度的均方根误差。另外1s处的均方根误差是1s这个时刻的还是25个预测点中前5个的均值？

**Comment by T-urning** [comment]
1. 将预测的速度转化成位置的代码可见：https://github.com/T-urning/SIT_TrajectoryPrediction/blob/ac3362fb176562ab10c49d8a9ddac76ed12af52d/main.py#L152
2. 1s 这个时刻。例如第一秒的误差就是 25 个预测点中第 5 个点的误差，第二秒对应第 10 个预测点，以此类推。

**Comment by Ocean728** [comment]
好的，谢谢解答
