### ISSUE TITLE
数据可视化文件

### ISSUE THREAD

**Issue by halcyonfreed** [T-urning/SIT_TrajectoryPrediction#3]
作者方便把数据可视化的npy/np文件生成部分的代码开源嘛，非常感谢

**Comment by T-urning** [comment]
不好意思哈，这部分代码我也没有保存，因为我是在模型预测时，用调试模式在相应的模型计算步骤打断点，然后用 np.save 保存该步骤的结果数据

**Comment by halcyonfreed** [comment]
哦哦 好的 谢谢
