### ISSUE TITLE
question

### ISSUE THREAD

**Issue by LzyhzfOliver** [T-urning/SIT_TrajectoryPrediction#4]
1.feeder_ngsim.py 请问按照Deo 提供的 MATLAB 脚本 ([preprocess_data.m](https://github.com/nachiket92/conv-social-pooling))，得到的tracks中的每个元组的第一维度是3维的，但是您提供的trainset，valset, testset中的维度是4维的。preprocess_data.m中的第180，190和200行显示的是3维。
2.attention.py 请问为什么将slf_attn_mask设成一个下三角包括对角线为True的矩阵，如果考虑时间的影响，不应该是一个上三角矩阵吗？
3.代码中对于原始数据使用了除以最大值的归一化方法把数据压缩成（0，1]，但Decoder部分对预测结果使用tanh激活函数，把数据压缩到(-1,1)之间，然后计算RMSE，请问这样做的原因是什么呢？

**Comment by T-urning** [comment]
您好，感谢您的认真阅读，希望能有帮助：
（1）是的，Deo 提供的 MATLAB 脚本 ([preprocess_data.m](https://github.com/nachiket92/conv-social-pooling)) 处理后的数据是三维的，我提供的是我对该脚本修改后生成的数据，修改只是增加了第四维数据（车道号 land_id，用作实验），并不影响前三维数据。这里有所体现：https://github.com/T-urning/SIT_TrajectoryPrediction/blob/ac3362fb176562ab10c49d8a9ddac76ed12af52d/feeder_ngsim.py#L185。

（2）是的，经过你的提醒，我才发现自己采用的是 tanh 函数，这会造成模型输出范围与目标范围不一致，会一定程度上影响模型效果，可以考虑换成 ReLU 或 Softplus 一类的激活函数；
在代码中，模型预测的是车辆的速度，并不直接是平面坐标，因此，在模型预测速度后，会将速度序列转化成坐标序列，RMSE 是在预测的坐标序列和真实的坐标序列上计算的，具体代码可见：https://github.com/T-urning/SIT_TrajectoryPrediction/blob/ac3362fb176562ab10c49d8a9ddac76ed12af52d/main.py#L152。

（3）第 n 个 step 对应的 subsequent_mask 是 slf_attn_mask 的第 n 行，而非第 n 列，所以 slf_attn_mask 是一个下三角+对角线的矩阵。例如，第一个 step 只与自己有关（slf_attn_mask 第一行），第二个 step 与第一个 step 及其自身有关（第二行）。
