### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by YangTongrui0124** [T-urning/SIT_TrajectoryPrediction#5]
您好，我最近在做轨迹预测方面的研究，复现了您的这篇论文，想向您请教几个问题：
1.请问您的代码运行了多久，我在20G显卡的服务器上运行，进度非常缓慢，一天大概跑6个epoch，跑完300个可能需要50多天。想咨询一下这是正常情况，还是我实验出现了问题。
2.请问数据预处理部分，您参考的deo代码有原始数据集吗？他采用的matlab文件中，需要首先对数据按照路段名称进行分类，现在NGSIM官网下载的数据不支持分类下载了。我想了解一下本文所用数据集所包含的高速公路场景，以及处理数据的过程中如何将数据集扩充到那么大的数据量。
非常感谢您的回复，希望您可以直接回复，或和我通过邮箱交流！2462717923@qq.com

**Comment by T-urning** [comment]
1. 正常，因为数据量很大，训练时数据集不是一次性处理好再加载到内存中，而是在训练过程中挨个 batch 地处理，这部分会花比较多时间，也挺消耗 CPU。

2. 具体处理细节请参考 deo 的代码，原始数据下载链接如下：

- [US-101-LosAngeles-CA.zip](https://data.transportation.gov/api/views/8ect-6jqj/files/bf7ca201-c7b3-4dc0-8f77-578f7794fcee?download=true&filename=US-101-LosAngeles-CA.zip)
- [I-80-Emeryville-CA.zip](https://data.transportation.gov/api/views/8ect-6jqj/files/10ed9f47-ab08-4df2-b46a-29f1683ceffa?download=true&filename=I-80-Emeryville-CA.zip)

**Comment by YangTongrui0124** [comment]
> 1. 正常，因为数据量很大，训练时数据集不是一次性处理好再加载到内存中，而是在训练过程中挨个 batch 地处理，这部分会花比较多时间，也挺消耗 CPU。
> 2. 具体处理细节请参考 deo 的代码，原始数据下载链接如下：
> 
> * [US-101-LosAngeles-CA.zip](https://data.transportation.gov/api/views/8ect-6jqj/files/bf7ca201-c7b3-4dc0-8f77-578f7794fcee?download=true&filename=US-101-LosAngeles-CA.zip)
> * [I-80-Emeryville-CA.zip](https://data.transportation.gov/api/views/8ect-6jqj/files/10ed9f47-ab08-4df2-b46a-29f1683ceffa?download=true&filename=I-80-Emeryville-CA.zip)

非常感谢您的回复，还想咨询您一个问题，您在论文中提到该实验的输入变量中包含速度信息，请问这个是在deo的数据处理代码中做了修改吗？您提供的百度网盘中的数据集似乎对应的是deo的代码处理结果，其中有47列特征，没有关于速度的数据。我是交通专业的研究生，我也觉得加入速度信息是有道理的！

**Comment by T-urning** [comment]
速度是直接在训练过程中实时算的，可以看这里：

https://github.com/T-urning/SIT_TrajectoryPrediction/blob/ac3362fb176562ab10c49d8a9ddac76ed12af52d/main.py#L80
